"""{{project}} exception classes."""

class {{package.capitalize()}}Error(Exception):
    """Generic errors."""
    def __init__(self, value, code=1):
        Exception.__init__(self)
        self.msg = value
        self.code = code
    
    def __str__(self):
        return self.msg
        
    def __unicode__(self):
        return unicode(self.msg)
                
class {{package.capitalize()}}ConfigError({{package.capitalize()}}Error):
    """Config parsing and setup errors."""
    def __init__(self, value):
        code = 10
        {{package.capitalize()}}Error.__init__(self, value, code)

class {{package.capitalize()}}RuntimeError({{package.capitalize()}}Error):
    """Runtime errors."""
    def __init__(self, value):
        code = 20
        {{package.capitalize()}}Error.__init__(self, value, code)
        
class {{package.capitalize()}}InternalServerError({{package.capitalize()}}Error):
    """Unknown or private internal errors."""
    def __init__(self, value):
        code = 30
        {{package.capitalize()}}Error.__init__(self, value, code)
        
class {{package.capitalize()}}ArgumentError({{package.capitalize()}}Error):
    """Argument errors."""
    def __init__(self, value):
        code = 40
        {{package.capitalize()}}Error.__init__(self, value, code)
